In [2]:
import numpy as np
A = np.array([[1,2,3],[3,4,5]])
print(A)


[[1 2 3]
 [3 4 5]]


In [3]:
array =np.zeros( (2,3) )
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
array =np.ones( (1,5) )
print(array)


[[1. 1. 1. 1. 1.]]


In [5]:
n = int(input("Kac Adet Sayi Girilecek: "))
a = []
for i in range(0,n):
    elem = int(input("Sayi Giriniz: "))
    a.append(elem)
avg = sum(a) / n
print("Girilen Sayilarin Ortalamasi: ", round(avg,2))

Kac Adet Sayi Girilecek: 3
Sayiyi Girin: 15
Sayiyi Girin: 20
Sayiyi Girin: 30
Girilen Sayilarin Ortalamasi:  21.67
